module.exports = [
    {
    id: 1,
    name: 'Killarney Raspberry',
    care_instructions: 'MORE TBD',
    info: 'The Killarney raspberry is a hearty fruit that can survive in extremely cold climates - in many cases, it will even live through your frosty winter! Raspberries need time to get used to their new home, so it will likely take a season before you can harvest fruit',
    category: 'Fruit',
    needs_trellis: false,
    image: 'http://localhost:8080/images/raspberry-killarney.jpg',
  },
  {
    id: 2,
    name: 'Encore Raspberry',
    care_instructions: 'MORE TBD',
    info: 'These berries are known to be super sweet and are often used to make pie filling & homemade jams. Raspberries need time to get used to their new home, so it will likely take a season before you can harvest fruit.',
    category: 'Fruit',
    needs_trellis: false,
    image: 'http://localhost:8080/images/raspberry-encore.jpeg'
  },
  {
    id: 3,
    name: 'Wild Strawberry',
    care_instructions: 'MORE TBD',
    info: "Wild strawberries are seedless and slightly smaller than the typical strawberries you'll find at a grocery store - but are still sweet & flavourful. Strawberries need time to get used to their new home, so it will likely take a season before you can harvest fruit.",
    category: 'Fruit',
    needs_trellis: false,
    image: 'http://localhost:8080/images/strawberry-wild.jpeg'
  },
  {
    id: 4,
    name: 'Kent Strawberry',
    care_instructions: 'MORE TBD',
    info: 'Kent strawberries are a medium sized strawberry that is packed with flavour - enjoy with some jam or on its own! Strawberries need time to get used to their new home, so it will likely take a season before you can harvest fruit.',
    category: 'Fruit',
    needs_trellis: false,
    image: 'http://localhost:8080/images/strawberry-kent.jpeg'
  },
  {
    id: 5,
    name: 'Prairie Sensation Apple',
    care_instructions: 'MORE TBD',
    info: 'Known to produce apples that are juicy, crisp, and have a lovely sweet flavor. The apples that are formed are round in shape, and range from yellow to green in color, with a reddish overlay. This tree is a cold hardy tree. Great option for you if you are looking for apples that are great for fresh eating, or used in pies.',
    category: 'Fruit',
    needs_trellis: false,
    image: 'http://localhost:8080/images/tree-prairie-sensation-apple.jpeg'
  },
  {
  id: 6,
  name: 'Treasured Red Columnar Apple',
  care_instructions: 'TBD',
  info: "Columnar Apple has an exquisite texture and a flavour similar to a McIntosh apple. Super compact, they fit easily into small urban gardens or along fences and decks. Unlike traditional apples that grow on horizontal branches, the Treasured Red bares fruit on short spurs that develop along the main tree trunk",
  category: 'Fruit',
  needs_trellis: false,
  image: "http://localhost:8080/images/apple_treasured_red.jpeg"
},
{
  id: 7,
  name: "Blackcurrant",
  care_instructions: "TBD",
  info: "Blackcurrant is a medium-sized shrub producing delicious, deep purple to black sweet berries suitable for jams, jellies, syrups and cordial.",
  category: "Currant",
  needs_trellis: false,
  image: "http://localhost:8080/images/blackcurrant-image.jpeg",
},
{
  id: 8,
  name: "Northline Saskatoon",
  care_instructions: "TBD",
  info: "Northline Saskatoon is a native shrub that's famous for its great-tasting fruit. The berries are terrific for fresh eating and cooking. The Saskatoon bush itself can be quite large and produces an abundance of fruit. Saskatoons are hardy and can tolerate partial shade and a variety of growing conditions.",
  category: "Berry",
  needs_trellis: false,
  image: "http://localhost:8080/images/northline-saskatoon-berry.jpeg",
},
{
  id: 9,
  name: "Manchurian Apricot",
  care_instructions: "TBD",
  info: "Manchurian Apricot is a winter-hardy relative of the native plum. This tree can stand some drought, but will not handle standing water or saturated moist soils. It can be used in shelterbelts, hedges, or as an ornamental. Manchurian Apricot will also attract songbirds, rabbits, and other rodents if left uncontrolled.",
  category: "Fruit",
  needs_trellis: false,
  image: "http://localhost:8080/images/manchurion-apricot.jpeg",
},
{
  id: 10,
  name: "Sour Cherry",
  care_instructions: "TBD",
  info: "Sour Cherry is ideal for cooking, preserves, or for making juices and jams, while sweet cherries are preferred for fresh eating. While we can't confirm claims of sour cherries medical benefits, studies have shown that sour cherries contain anti-inflammatory properties and can help regulate sleep patterns.",
  category: "Fruit",
  needs_trellis: false,
  image: "http://localhost:8080/images/sour-cherry.jpeg",
},
{
  id: 11,
  name: "Crimson Passion Cherry",
  care_instructions: "TBD",
  info: "The Crimson Passion Cherry is a hardy deciduous hybrid dwarf Sour Cherry. This medium-sized self-pollinator produces tart, bright red fruits in large clusters in late summer that are perfect for jams, pies and jellies. Crimson Passion Cherry is ideal as a landscape or orchard tree.",
  category: "Fruit",
  needs_trellis: false,
  image: "http://localhost:8080/images/carmine-cherry.jpeg",
},
{
  id: 12,
  name: "Siberean C Peach",
  care_instructions: "TBD",
  info: "The Siberian C Peach is a cold hardy peach cultivar, and the fruit is great for producing juice and fresh eating. This variety is native to the Gobi desert area of China, and is relatively true to seed. In colder climates they might not grow fruit reliably as they require a relatively hot summer for the fruit to produce.",
  category: "Fruit",
  needs_trellis: false,
  image: "http://localhost:8080/images/siberean-peach.jpeg",
},
{
  id: 13,
  name: "Goji Berry",
  care_instructions: "TBD",
  info: "The Dynamite Goji Berry is a thornless cultivar of the Goji Berry known for its hearty, brilliant-red berries. This deciduous perennial produces white/lavender flowers that bloom from June through September, with fruit maturation taking place between August and October. Fruit production typically starts in the second year of growth with maximum production in the fourth and fifth year. Dynamite Goji Berry berries are delicious, nutrient rich, high in antioxidants, and are often called a super fruit. Many describe their flavour as being like a tart cherry tomato.",
  category: "Fruit",
  needs_trellis: false,
  image: "http://localhost:8080/images/goji_berry_dynamite.jpeg",
},
{
  id: 14,
  name: "Beaked Hazelnut",
  care_instructions: "TBD",
  info: "Beaked Hazelnut is a multi-stemmed, deciduous shrub native to North America. It features smooth, grey bark and edible nuts. Beaked Hazelnut prefers a rich sandy-clay loam but will grow on poorer sites, and can be used as an understory shrub. Note: You want more than one hazelnut to improve yields.",
  category: "Nut",
  needs_trellis: false,
  image: "http://localhost:8080/images/hazelnut_beaked.jpeg",
},
{
  id: 15,
  name: "Bog Cranberry",
  care_instructions: "TBD",
  info: "Bog Cranberry is a native, ground cover species. These plants generally produce one crop per year in summer. Plants may spread 3 feet in width forming a dense mat which makes it attractive as an ornamental ground cover. Bog Cranberry flowers are similar in shape to those of blueberry and may be white or pink in color. These berries are considered to be highly flavored but not as tart as cranberries.",
  category: "fruit",
  needs_trellis: false,
  image: "http://localhost:8080/images/cranberry_bog.jpeg",
},
]


// {
//   id: ,
//   name: "",
//   care_instructions: "TBD",
//   info: "",
//   category: "",
//   needs_trellis: ,
//   image: "http://localhost:8080/images/",
// },