module.exports = [
    {
        id: 1,
        plant_id: 1,
        no_direct_sun: 0,
        under_two_hours: 0,
        two_to_four_hours: 0,
        four_to_eight_hours: 1,
        eight_plus_hours: 1,
    },
    {
        id: 2,
        plant_id: 2,
        no_direct_sun: 0,
        under_two_hours: 0,
        two_to_four_hours: 0,
        four_to_eight_hours: 0,
        eight_plus_hours: 2,
    },
    {
        id: 3,
        plant_id: 3,
        no_direct_sun: 0,
        under_two_hours: 0,
        two_to_four_hours: 0,
        four_to_eight_hours: 0,
        eight_plus_hours: 2,
    },
    {
        id: 4,
        plant_id: 4,
        no_direct_sun: 0,
        under_two_hours: 0,
        two_to_four_hours: 0,
        four_to_eight_hours: 1,
        eight_plus_hours: 1,
    },
    {
        id: 5,
        plant_id: 5,
        no_direct_sun: 0,
        under_two_hours: 0,
        two_to_four_hours: 0,
        four_to_eight_hours: 0,
        eight_plus_hours: 1,
    },
    {
    id: 6,
    plant_id: 6,
    no_direct_sun: 0,
    under_two_hours: 0,
    two_to_four_hours: 0,
    four_to_eight_hours: 0,
    eight_plus_hours: 1,
  },
  {
    id: 7,
    plant_id: 7,
    no_direct_sun: 0,
    under_two_hours: 0,
    two_to_four_hours: 1,
    four_to_eight_hours: 1,
    eight_plus_hours: 1,
  },
  {
    id: 8,
    plant_id: 8,
    no_direct_sun: 0,
    under_two_hours: 0,
    two_to_four_hours: 0,
    four_to_eight_hours: 1,
    eight_plus_hours: 1,
  },
  {
    id: 9,
    plant_id: 9,
    no_direct_sun: 0,
    under_two_hours: 0,
    two_to_four_hours: 0,
    four_to_eight_hours: 1,
    eight_plus_hours: 1,
  },
  {
    id: 10,
    plant_id: 10,
    no_direct_sun: 0,
    under_two_hours: 0,
    two_to_four_hours: 1,
    four_to_eight_hours: 1,
    eight_plus_hours: 1,
  },
  {
    id: 11,
    plant_id: 11,
    no_direct_sun: 0,
    under_two_hours: 0,
    two_to_four_hours: 1,
    four_to_eight_hours: 1,
    eight_plus_hours: 1,
  },
  {
    id: 12,
    plant_id: 12,
    no_direct_sun: 0,
    under_two_hours: 0,
    two_to_four_hours: 0,
    four_to_eight_hours: 1,
    eight_plus_hours: 1,
  },
  {
    id: 13,
    plant_id: 13,
    no_direct_sun: 0,
    under_two_hours: 0,
    two_to_four_hours: 1,
    four_to_eight_hours: 1,
    eight_plus_hours: 1,
  },
  {
    id: 14,
    plant_id: 14,
    no_direct_sun: 0,
    under_two_hours: 0,
    two_to_four_hours: 1,
    four_to_eight_hours: 1,
    eight_plus_hours: 1,
  },
  {
    id: 15,
    plant_id: 15,
    no_direct_sun: 0,
    under_two_hours: 0,
    two_to_four_hours: 1,
    four_to_eight_hours: 1,
    eight_plus_hours: 1,
  },
]

// {
//     id: ,
//     plant_id: ,
//     no_direct_sun: ,
//     under_two_hours: 0,
//     two_to_four_hours: 0,
//     four_to_eight_hours: 0,
//     eight_plus_hours: 0,
//   },